version: 0.2

phases:
  pre_build:
    commands:
      - echo Pulling Docker Images for cache 

  build:
    commands:
      - docker-compose build
  post_build:
    commands:
      - docker-compose up -d
