version: '3.3'

services:
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "monitoramento"
      MYSQL_DATABASE: "monitoramento"
    ports:
      - "3305:3306"
    restart: always
    networks:
      - backend
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend
      
  eureka-service:
    image: sga/eureka-service:latest
    ports:
      - "8761:8761"
    restart: always
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
       
  zuul-gateway:
    depends_on:
      - eureka-service
    image: sga/zuul-gateway:latest
    ports:
      - "8765:8765"
    restart: always
    environment:
     EUREKA_URI: http://eureka-service:8761/eureka
    networks:
      - backend

  seguranca-comunicacao-service:
    depends_on:
      - mysql
      - eureka-service
      - rabbitmq
    image: sga/seguranca-comunicacao-service:latest
    ports:
      - "8060:8060"
    restart: always
    environment:
     EUREKA_URI: http://eureka-service:8761/eureka
     RABBIT_HOST: rabbitmq
    networks:
      - backend

  monitoramento-service:
    depends_on:
      - mysql
      - eureka-service
    image: sga/monitoramento-service:latest
    ports:
      - "8061:8061"
    restart: always
    environment:
     EUREKA_URI: http://eureka-service:8761/eureka
    networks:
      - backend
      
  cadastro-ativos-service:
    depends_on:
      - mysql
      - eureka-service
    image: sga/cadastro-ativos-service:latest
    ports:
      - "8069:8069"
    restart: always
    environment:
     EUREKA_URI: http://eureka-service:8761/eureka
    networks:
      - backend

  notificacao-service:
    depends_on:
      - eureka-service
      - rabbitmq
    image: sga/notificacao-service:latest
    ports:
      - "8062:8062"
    restart: always
    environment:
     EUREKA_URI: http://eureka-service:8761/eureka
     RABBIT_HOST: rabbitmq
    networks:
      - backend

  monitoramento-ui:
    depends_on:
      - mysql
      - eureka-service
      - zuul-gateway
      - seguranca-comunicacao-service
      - monitoramento-service
      - cadastro-ativos-service
    image: sga/monitoramento-ui:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
     WS_SEGURANCA: http://zuul-gateway:8765/api
    networks:
      - backend


networks:
  backend:
    driver: "bridge"